### ISSUE TITLE
Instruction Implementations

### ISSUE THREAD

**Issue by TheEmeraldBee** [TheEmeraldBee/UVSim#3]
After #2 is completed, we need to implement each instruction

- [x] Read: 10, read keyboard into memory location
- [x] Write: 11, write memory location value to screen
- [x] Load: 20, load value into accumulator from memory location
- [x] Store: 21, store value in accumulator in memory location
- [x] Add: 30, increment accumulator by value in memory location
- [x] Subtract: 31, subtract accumulator by value in memory location
- [x] Divide: 32, divide accumulator by value in memory location
- [x] Multiply: 33, multiply accumulator by value in memory location
- [x] Branch: 40, go to given memory location
- [x] BranchNeg: 41, go to given memory location if accumulator is negative
- [x] BranchZero: 42, go to given memory location if accumulator is 0
- [x] Halt: 43, pause program

**Comment by Natmanatwork** [comment]
I'll do Add, Subtract, Multiply, & Divide.

**Comment by TheEmeraldBee** [comment]
I'll do Halt and Read

**Comment by BradyShimanek** [comment]
I'll do Branch, BranchNeg, and BranchZero
