### ISSUE TITLE
Check for Doc-Strings

### ISSUE THREAD

**Issue by TheEmeraldBee** [TheEmeraldBee/UVSim#37]
Ensure each class and function has basic description of goals via Doc-String

**Comment by FelipeCotrina** [comment]
Added Doc-Strings for ColorConfig class; AddInstruction class; BranchNegInstruction class; BranchZeroInstruction class; BranchInstruction class; DivisionInstruction class; HaltInstruction class; LoadInstruction class; MultiplyInstruction class; ReadInstruction class; StoreInstruction class; SubtractInstruction class; WriteInstruction class; InstructionEvent class; Instruction class; InstructionParsingError class; EditorTab class; RunTab class; Tabs class to improve clarity and documentation.
